version: "3.8"
# For Database only
services:
  mysql:
    image: mysql
    container_name: xe_clone
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
    driver: local
