# Generated by Django 4.2.14 on 2024-08-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
