# Generated by Django 4.2.14 on 2024-08-08 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
